# Site settings
title: Data Analyst
description: Blog, projects and more about data analysis and web pages
baseurl: "/framsses_projects" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ramsses Ayala
user_description: Mathematician interested in Data Analytics and Responsive Web Design. Work together in the organization, evaluation and application of solutions for different opportunities that a company, business, institution or person has. In the same way, participate actively and formally in a professional, economic, academic and social environment. I'm currently learning and improving my English skills in an education center.
user_title: Data Analyst & Web Developer Jr
email: framsses@hotmail.com
year: 2022
linkedin_username: francisco-ramsses-ayala-romero-6b8662162
github_username:  framsses

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
